### PR TITLE
feat/upgrade-to-gatsby-4

### PR DESCRIPTION
**Pull request by PaulieScanlon**
- upgrade core to Gatsby 4
- update plugins to latest
- add [gatsby-plugin-netlify](https://github.com/netlify/netlify-plugin-gatsby/#caveats)
- add DSG `defer: true` to `gatsby-node`

### CODE REVIEW

**Comment by PaulieScanlon** [comment]
Oh blast! I see the build failed. Perhaps clearing the cache and running it again will do the trick.

**Comment by mgreiler** [comment]
I've cleared the cache and redeployed. Fingers crossed it comes back successful!
Thanks for your contribution!

**Comment by PaulieScanlon** [comment]
Hey. Hmmm. I wonder if this is a Netlify thing 🤔. Running the build locally works fine. I know that's not terribly helpful but it usually gives some indication of where the problems are.

**Comment by PaulieScanlon** [comment]
Hey, I was just having a read of the `gatsby-plugin-netlify` docs, and one thing that might be causing a problem is...

The docs state:
> New Gatsby sites on Netlify automatically install the Essential Gatsby build plugin

If your site isn't "new" -- and i'm not sure what that means, you might need to install the build plugin manually. 

There are x2 options. [Installing the Netlify build plugin](https://github.com/netlify/netlify-plugin-gatsby#installing-the-netlify-build-plugin)

**Comment by PaulieScanlon** [comment]
Hey again... i was curios to test out what "new" meant so i spun up a "new" site on my own Netlify account. I'm seeing similar errors. https://github.com/PaulieScanlon/se-unlocked-website/pull/2

I can't for sure say either way where the problem is but i'll continue to investigate.

**Comment by mgreiler** [comment]
Hi @PaulieScanlon, thanks for your investigation. 

One thing I was wondering is if we can locate the problem by splitting it up into the distinct changes:

- upgrade core to Gatsby 4
- update plugins to latest
- add [gatsby-plugin-netlify](https://github.com/netlify/netlify-plugin-gatsby/#caveats)
- add DSG defer: true to gatsby-node

When you spun up the new site, could you say which one of those is causing the issue? 

Thank you!

**Pull request closed without merging**
